dbmspr/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('homepage.urls')),
    path('admin/', admin.site.urls),
]

homepage/urls.py
from django.urls import path
from . import views
app_name = 'homepage'
urlpatterns=[
    path('',views.home, name='home'),
    path('/submit', views.submit, name='submit' )
]

homepage/models.py
from django.db import models

class Data(models.Model):
    name=models.CharField(max_length=300)
    email=models.TextField(unique=True)
    num=models.IntegerField()
# Create your models here.

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Data
# Create your views here.

def home(request):
        return render(request,'linkinpark.html')

def submit(request):
    if request.method == 'POST':
        name = request.POST["name"]
        email = request.POST["email"]
        num= request.POST["number"]
                
        created_obj = Data.objects.create(name = name, email = email, num=num)
    return render(request,"linkinpark.html")

templates/linkinpark.html
<!DOCTYPE html>
<html>
<head>
    <title>Linkin Park</title>
    <link rel = "icon" href =  
"https://scontent.fdel10-1.fna.fbcdn.net/v/t31.0-8/20229456_1450780658322674_6982274811954342936_o.jpg?_nc_cat=102&ccb=2&_nc_sid=09cbfe&_nc_ohc=5_QSq2Ut02sAX_uaGM8&_nc_ht=scontent.fdel10-1.fna&oh=9da620e96f1f64bbe0ff2f1a17e3c03d&oe=5FCC1966" 
        type = "image/x-icon">
<meta name="viewport"
content="width=device-width, initial-scale=1.0">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

.form-inline {  
  display: flex;
  flex-flow: row wrap;
  align-items: center;
}

.form-inline label {
  margin: 5px 10px 5px 0;
}

.form-inline input {
  vertical-align: middle;
  margin: 5px 10px 5px 0;
  padding: 10px;
  background-color: #fff;
  border: 1px solid #ddd;
}

.form-inline button {
  padding: 10px 20px;
  background-color: dodgerblue;
  border: 1px solid #ddd;
  color: white;
  cursor: pointer;
}

.form-inline button:hover {
  background-color: royalblue;
}

@media (max-width: 800px) {
  .form-inline input {
    margin: 10px 0;
  }
  
  .form-inline {
    flex-direction: column;
    align-items: stretch;
  }
}
.para
{
text-align:left;
font-size:20px;
}
a:link
{
color:white;

background-color:black;
text-decoration:bold;
font-size:20px;
}
body{
color:white;
text-align:center;
background-image:url('https://i2.wp.com/www.xsnoize.com/wp-content/uploads/2020/02/GreyDaze_14x9_300dpi_RGB-Tom-Preston.jpg?resize=678%2C381&ssl=1');
background-repeat: no-repeat;
background-size: cover;
}
</style>
<img src="https://www.linkinpark.com/sites/g/files/g2000008491/files/opt_link_image.jpg";
width=100%; height=500;
border=1;
border-style=rounded;
border-width=medium;><br><br>
<nav>
<a href="https://en.wikipedia.org/wiki/Linkin_Park">Wikipedia page of band</a>|  |
<a href="https://www.linkinpark.com/">Official page of band</a>
</nav>
</head>
<p style=font-size:20px;>The band has been an utter success in the era but has lost values in the recent time. Here are top 10 songs of the band to commemorate them.</p>
<hr>
<h1 style=text-align:left>1.Numb</h1>
<p class="para">"Numb" is a song by American rock band Linkin Park. It was released as the third single from their second studio album, Meteora (2003), and is the closing track on the album. One of Linkin Park's most well-known and critically acclaimed songs, "Numb" topped the Billboard Alternative Songs chart for 12 weeks.[3] The song spent six weeks at the top of the chart in 2003 and six weeks in 2004. The song also spent three weeks atop the Billboard Hot Mainstream Rock Tracks chart and peaked at number 11 on the Billboard Hot 100. As of April 2020, the song has over 1.3 billion views and 8 million likes on YouTube.</p>
<a href="https://www.youtube.com/watch?v=kXYiU_JCYtU";
title="click me";
target="_blank";>
<img src="https://static.billboard.com/files/media/linkin-park-numb-MV-vid-2018-billboard-1548-768x433.jpg"
width=50%; height=433;
border=1;>
</a>
<br>
<h1 style=text-align:left>2.In the End</h1>
<p class="para">"In the End" is a song by American rock band Linkin Park. It is the eighth track on their debut album Hybrid Theory (2000) and was released as the album's final single. "In the End" is one of Linkin Park's most recognisable and signature songs. It is the most played song in all of the band's live performances, "One Step Closer" coming in close second.</p>
<a href="https://www.youtube.com/watch?v=eVTXPUF4Oz4";
title="click me";
target="_blank";>
<img src="https://upload.wikimedia.org/wikipedia/en/3/3f/LinkinParkIntheEnd.jpg"
width=50%; height=316;
border:1;>
</a>
<h1 style=text-align:left>3. Castle of glass </h1>
<p class="para">"Castle of Glass" is a song written by American rock band Linkin Park for their fifth studio album, Living Things.[1] The song was produced by co-lead vocalist Mike Shinoda[2] and Rick Rubin. The song was released as a promotional single for Danger Close Games's 2012 release, Medal of Honor: Warfighter, as with Linkin Park's previous contribution to the Medal of Honor series, "The Catalyst". The single was released on February 2, 2013 in physical format[3] and on March 22, 2013 it was released as a digital single on iTunes.</p>
<a href="https://www.youtube.com/watch?v=ScNNfyq3d_w";
title="click me";
target="_blank";>
<img src="https://i1.sndcdn.com/artworks-000159086133-5tkuc1-t500x500.jpg"
width=50%; height=500;
border=1;>
</a>
<h1 style=text-align:left>4. The Catalyst</h1>
<p class="para">The Catalyst" is a song by the American rock band Linkin Park. Released on August 2, 2010,[5] it is the first single from their fourth studio album, A Thousand Suns, which was released on September 8, 2010. The music video for the song, directed by the band's turntablist Joe Hahn, was released on August 25, 2010.
"The Catalyst" is used in the trailer and credits of the video game Medal of Honor and also the opening song of Namco-Bandai's Arcade game, Mobile Suit Gundam: Extreme Vs.. It was also used in select commercials of the Discovery Channel series, Surviving the Cut. The song was also featured in the video game Linkin Park Revenge for the iPhone, iPad, and iPod Touch. "The Catalyst" has also been used in the advertisement for the 2011 movie The Lincoln Lawyer with Matthew McConaughey.</p>
<a href="https://www.youtube.com/watch?v=51iquRYKPbs";
title="click me";
target="_blank";>
<img src="https://upload.wikimedia.org/wikipedia/en/c/cd/The-catalyst-single-cover-500x500.png"
width=50%; height=316;
border=1;>
</a>
<h1 style=text-align:left>5. What I've Done</h1>
<p class="para">"What I've Done" is a song by American rock band Linkin Park. It was released as the first single from their third studio album Minutes to Midnight (2007), and is the sixth track. The song is composed in the key of G minor. The song was released as a radio single on April 1, 2007, as a digital download on April 2, and as a CD single on April 30. The live version of "What I've Done" from Road to Revolution: Live at Milton Keynes was nominated for Best Hard Rock Performance at the 52nd Grammy Awards, but did not win.[2] It also serves as the main theme of the 2007 science fiction film Transformers and also appears on Transformers: The Album (2007).[3] Being certified five times platinum by the RIAA, it is the band's most commercially successful song, though not necessarily most well-known, due to the fact that singles in the US used to have higher sales in general during the second-half of the 2000s.</p>
<a href="https://www.youtube.com/watch?v=8sgycukafqQ";
title="click me";
target="_blank";>
<img src="https://i.ytimg.com/vi/_ulTNFrMj80/hqdefault.jpg";
width=50%; height=360;
border=1;>
</a>
<h1 style=text-align:left>6. One step closer</h1>
<p class="para">"One Step Closer" is the debut single by the American rock band Linkin Park. It was released as the first single and second track of their debut album, Hybrid Theory.[3] The song was featured in the 2008 music video games Rock Band 2 and Guitar Hero On Tour: Decades, and the soundtrack to the 2000 film Dracula 2000 in the end credits.<br>Until 2007, Linkin Park closed every concert with "One Step Closer", excluding Live 8, and their live performances at Summer Sonic. In 2007, Linkin Park played "One Step Closer" toward the beginning of their live performances and sometimes at the end. The song is always played in Drop C#. In 2008, they ended some of their shows with either "One Step Closer" or "Bleed It Out". In 2009, every show they played was ended with "One Step Closer", excluding the Transformers: Revenge of the Fallen premiere.</p>
<a href="https://www.youtube.com/watch?v=4qlCC1GOwFw";
title="click me";
target="_blank";>
<img src="https://upload.wikimedia.org/wikipedia/en/1/1a/Linkin_Park_-_One_Step_Closer_CD_cover.jpg"
width=50%; height=350;
border=1;>
</a>
<h1 style=text-align:left>7. Burn It Down</h1>
<p class="para">"Burn It Down" is a song by American rock band Linkin Park. The song was released to radio stations, as well as a digital download,[1] on April 16, 2012, as the lead single from their fifth studio album Living Things. The song was written by the band and produced by co-lead vocalist Mike Shinoda and Rick Rubin,[4] who co-produced the band's studio albums Minutes to Midnight (2007) and A Thousand Suns (2010). A music video for the song was directed by Linkin Park turntablist Joe Hahn.[5][6] As of February 13, 2013, "Burn It Down" had sold over one million copies in the United States, making it their eighth single to be certified gold by the RIAA.</p>
<a href="https://www.youtube.com/watch?v=dxytyRy-O1k";
title="click me";
target="_blank";>
<img src="https://upload.wikimedia.org/wikipedia/en/9/98/Linkin_Park_Burn_It_Down.jpg";
width=50%; height=350;
border=1;>
</a>
<h1 style=text-align:left>8. Crawling</h1>
<p class="para">"Crawling" is a song by American rock band Linkin Park. It is the second single from their debut album Hybrid Theory and is the fifth track on the album. It was released in 2000 as their second single and won a Grammy for Best Hard Rock Performance in 2002. In January 2011, "Crawling" was released in a Linkin Park DLC pack for Rock Band 3.<br> "Crawling" is one of the few songs on Hybrid Theory that does not prominently feature Mike Shinoda's rap sung lyrics. The intro to "Crawling" has been remixed in live versions over the years. Since 2008's Projekt Revolution, Mike Shinoda has rapped the first verse of "Hands Held High" over the intro to Reanimation version of "Crawling", titled "Krwlng" (featuring Staind frontman Aaron Lewis). In 2009, Shinoda rapped two verses of "Hands Held High" over the intro of "Crawling", which first verse started with an a cappella or a bassline before the Reanimation intro started, in which Shinoda raps the second verse. Singer Chester Bennington remarked that "Crawling" was the most difficult Linkin Park song to sing live, stating "Crawling has caused me the most trouble live more than any other song." Bennington also commented on the meaning of "Crawling" by stating it was inspired by his own battles with substance abuse. "Crawling is about feeling like I had no control over myself in terms of drugs and alcohol, hence the line "These wounds they will not heal...".[3] The song is recorded in the key of C# minor.</p>
<a href="https://www.youtube.com/watch?v=Gd9OhYroLN0";
title="click me";
target="_blank";>
<img src="https://i1.sndcdn.com/artworks-000467138340-x1d04o-t500x500.jpg";
width=50%; height=500;
border=1;>
</a>
<h1 style=text-align:left>9. One more light</h1>
<p class="para">"One More Light" is a song by American rock band Linkin Park. It is the ninth and title track from their seventh studio album of the same name, as well as their last single with longtime lead vocalist Chester Bennington. The song was co-written with Eg White and was released to US contemporary hit radio on October 3, 2017 as the album's third single. It is Bennington's second posthumously released single.[1]
The music video for this song was also voted number one in a poll of Fuse Top 40 Videos of 2017 and is also nominated for Best Rock Video at the 2018 MTV Video Music Awards.</p>
<a href="https://www.youtube.com/watch?v=Tm8LGxTLtQk";
title="click me";
target="_blank";>
<img src="https://upload.wikimedia.org/wikipedia/en/4/46/One_More_Light_Remix.jpg";
width=50%; height=300;
border=1;>
</a>
<h1 style=text-align:left>10. Leave out all the rest</h1>
<p class="para">Leave Out All the Rest" is a song by the American rock band Linkin Park, which was released as the fifth and final single from their third album Minutes to Midnight. Because of the song's popularity of digital sales during the release week of the album, it charted in the Billboard Pop 100 for that week. On the album, the song segues into "Bleed It Out". The single was released on July 15, 2008.The song's working titles were "Fear" and "When My Time Comes" according to the booklet. While writing, the group went through over thirty lyrical variations before completing the album version. The song combines various synths and samples with raw guitars and drums and powerful vocals. A demo which features Mike Shinoda doing lead vocals can be heard on the Making of Minutes to Midnight documentary, as well as the Linkin Park Underground 9.0 CD where it is entitled "Fear". The song starts with a string sample and electric piano intro, followed by the verse. At the end of the song of the album version, a crowd can be heard which leads into "Bleed It Out", a song that features the background sound of a crowd throughout.</p>
<a href="https://www.youtube.com/watch?v=yZIummTz9mM";
title="click me";
target="_blank";>
<img src="https://vignette.wikia.nocookie.net/linkin-park-junior-underground/images/f/f8/Leave_Out_All_the_Rest.jpg/revision/latest/scale-to-width-down/340?cb=20150327053124";
width=50%; height=350;
border=1;>
</a>
<p style="font-size: 50px; text-align:left;"> Interested in attending the concert of the band?</p>
<p style="font-size: 30px; text-align:left;">We have got you covered, just enter your details in the following form. </p>
<form class="form-inline" style="text-align:left" action= "{% url 'homepage:submit' %} "method='POST'>
    {% csrf_token %}
    <label for="name">Enter your name:</label><br>
    <input type='text' placeholder='Name' name='name'> <br><br>
    <label for="name">Enter your email id:</label><br>
    <input type='email' placeholder='email' name='email'> <br><br>
    <label for="name">Enter your Phone number:</label><br>
    <input type='text' placeholder='Phone Number' name='number'><br><br>
    <input type='submit'>
</form>
<br>
<br>
<footer>
<p>Efforts by: Saaransh Shandilya<p>
  <p> Enrollment No.: 190020203039</p>
</footer>
</html>